mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('water.urls')),
    path('admin/', admin.site.urls),
]

water/urls.py
from django.urls import path, include
from . import views
from .views import *

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('allauth.urls')),
    path('logout/', views.logout, name='logout'),
    path('submit_water_station/', views.submit_water_station, name='submit_water_station'),
    path('map',views.map, name='map'),
    path('map/<str:place_id>/', views.MapStationsView.as_view(), name='map_stations'),
    path('approve_water_station/', views.approve_water_station, name='approve_water_station'),
    path('error/', views.error, name='error'),
    path('user_water_stations/', user_water_stations,name='user_water_stations'),
]

water/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.conf import settings

def get_null_user():
    return User.objects.get_or_create(username="NULL_USER")[0]

# blank = False requires column as a field in a form (cannot submit without)
# null = False requires column to have a value (cannot be NULL)
class Building(models.Model):
    name = models.CharField(max_length=500)
    lat = models.FloatField()
    lng = models.FloatField()
    place_id = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class WaterStation(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET(get_null_user)) # user who submitted, if user is deleted set to NULL_USER (dummy user)
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    floor = models.IntegerField(default=1, blank=False) # 0 is basement, 1 is first, etc., should limit in form
    CHOICES = (('c', 'Central area'), ('n', 'North side'), ('s', 'South side'), ('e', 'East side'), ('w', 'West side'))
    cardinal = models.CharField(max_length=1, blank=False, default=None, choices=CHOICES) # one of n, s, e, w, c (center of building)
    traditional = models.BooleanField() # true is bubbler / bottom part
    bottle = models.BooleanField() # true is vertical water bottle filler
    # image = models.ImageField(upload_to=MEDIA_ROOT, blank=True, null=True) # image of station, if NULL do not display
    approved = models.BooleanField() # true is approved and will show from map, false will show on admin approval page

water/forms.py
from django import forms
from .models import WaterStation, Building

# REFERENCE: https://docs.djangoproject.com/en/4.2/ref/forms/fields/

class WaterStationForm(forms.ModelForm):
    class Meta:
        model = WaterStation
        fields = ['building', 'floor', 'cardinal', 'traditional', 'bottle']
        widgets = {
            'floor': forms.TextInput(attrs={
                'min':0,
                'max':10,
                'type':'number',
            }),
            'cardinal': forms.RadioSelect(),
        }
        labels = {
            'building': 'What building is the station located in?',
            'floor':'What floor is the station on? (Enter 0 for basement level)',
            'cardinal':'What area of the floor is the station in?',
            'traditional':'Drinking dispenser',
            'bottle':'Bottle refill dispenser',
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""

    # def clean(self):
    #     clean_data = self.cleaned_data
    #     if not clean_data.get("traditional") and not clean_data.get("bottle"):
    #         raise forms.ValidationError("At least one dispenser type must be selected")
    #     return clean_data

class AdminApprovalForm(forms.ModelForm):
    class Meta:
        model = WaterStation
        fields = ['approved']

water/views.py
from django.forms import modelformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import user_passes_test
from .forms import AdminApprovalForm
from .models import WaterStation
from django.views import generic
from django.conf import settings
from .models import *
from .forms import *
from django.urls import reverse

# REFERENCE: https://medium.com/djangotube/django-roles-groups-and-permissions-introduction-a54d1070544
# REFERENCE: https://developers.google.com/maps/documentation/javascript/examples/event-simple

def is_admin(user):
    return user.is_authenticated and user.groups.filter(name='admin').exists()

def is_base(user):
    return user.is_authenticated and not user.groups.filter(name='admin').exists()

def is_logged_in(user):
    return user.is_authenticated

def map(request):
    key = settings.GOOGLE_API_KEY
    buildings = Building.objects.all()
    context = {
        'key': key,
        'buildings': buildings,
        'title': 'Map',
        'admin': is_admin(request.user),
    }
    return render(request, 'map.html', context)

class MapStationsView(generic.ListView):
    def get(self, request, place_id):
        stations = WaterStation.objects.filter(approved=True, building__place_id = place_id).order_by('floor')
        floors = WaterStation.objects.filter(approved=True, building__place_id = place_id).values('floor').distinct().order_by('floor')
        context = {
            'stations': stations,
            'floors': floors,
        }
        return render(request, 'map_stations.html', context)


def home(request):
    return render(request, 'home.html', { 'title': 'Home', 'admin': is_admin(request.user) })

def login(request):
    if not request.user.is_authenticated:
        return render(request, 'login.html', { 'title': 'Login' })
    else:
        # redirect logged-in user to home
        return redirect('/')

def logout(request):
    # call default logout for functionality
    auth_logout(request)
    # redirect logged-out user to home
    return redirect('/')

@user_passes_test(is_logged_in, login_url='error')
def submit_water_station(request):
    user_water_stations = WaterStation.objects.filter(user=request.user)
    key = settings.GOOGLE_API_KEY
    if request.method == 'POST':
        form = WaterStationForm(request.POST)
        if form.is_valid():
            water_station = form.save(commit=False)
            water_station.user = request.user
            if is_admin(request.user):
                water_station.approved = True  # Set approval status as True for admins
            else:
                water_station.approved = False  # Set approval status as False by default
            water_station.save()
            return redirect('submit_water_station')  # Redirect to the home page after submission
    else:
        form = WaterStationForm()
    context = {
        'form': form ,
        'key': key,
        'title': 'New Water Station',
        'admin': is_admin(request.user),
        'user_water_stations': user_water_stations,
    }
    return render(request, 'submit_water_station.html', context)


@user_passes_test(is_admin, login_url='error')
def approve_water_station(request):
    # filter not working on sqlite (boolean), OK on postgres so leave as is
    unapproved_water_stations = WaterStation.objects.filter(approved=False)

    if request.method == 'POST':
        admin_form = AdminApprovalForm(request.POST)  # Use the custom admin approval form
        if admin_form.is_valid():
            for water_station in unapproved_water_stations:
                approval_status = request.POST.get('radio-group-' + str(water_station.id))
                print(approval_status)
                if approval_status == 'approved':
                    water_station.approved = True
                    water_station.save()
                elif approval_status == 'rejected':
                    water_station.delete()
            return redirect('approve_water_station')
    else:
        admin_form = AdminApprovalForm()  # Use the custom admin approval form
        context = {
            'admin_form': admin_form,
            'unapproved_water_stations': unapproved_water_stations,
            'admin': is_admin(request.user),
            'title': 'Approve Water Stations',
        }
        return render(request, 'approve_water_station.html', context)

@user_passes_test(is_base, login_url='error')
def user_water_stations(request):
    user_water_stations = WaterStation.objects.filter(user=request.user)
    context = {
        'user_water_stations': user_water_stations,
        'title': 'Your Water Stations',
    }
    return render(request,'user_water_stations.html', context)

def error(request):
    return render(request, 'error.html', {'title':'Page not found'})

water/templates/approve_water_station.html
{% extends "base.html" %}
{% block content %}

<h2 class="text-center">Approve or Reject User-Submitted Water Stations</h2>
<script>
    if ( document.getElementById("navitem-home").classList.contains('active') ) {
        document.getElementById("navitem-home").classList.remove('active');
    }
    if (document.getElementById("navitem-map").classList.contains('active') ) {
        document.getElementById("navitem-map").classList.remove('active');
    }
    if ( document.getElementById("navitem-add").classList.contains('active') ) {
        document.getElementById("navitem-add").classList.remove('active');
    }
    if ( ! document.getElementById("navitem-approve").classList.contains('active') ) {
        document.getElementById("navitem-approve").classList.add('active');
    }
</script>
{% if unapproved_water_stations %}
    <form method="post">
        {% csrf_token %}
        <div class="bg-light text-black text-center mx-auto w-75 border border-2 mt-4">
            <ul class="list-unstyled">
                {% for water_station in unapproved_water_stations %}
                    <li class="mb-4 mt-2">
                        Submitted by: {{ water_station.user.email }}
                        <br>
                        Building: {{ water_station.building }}
                        <br>
                        Floor: {{ water_station.floor }}
                        <br>
                        Area: 
                        {% if water_station.cardinal == "c" %}
                            Central area of the building
                        {% elif water_station.cardinal == "n" %}
                            North side of the building
                        {% elif water_station.cardinal == "s" %}
                            South side of the building
                        {% elif water_station.cardinal == "e" %}
                            East side of the building
                        {% elif water_station.cardinal == "w" %}
                            West side of the building
                        {% endif %}
                        <br>
                        Dispenser types:
                        {% if water_station.bottle %}
                        Bottle
                        {% endif %}
                        {% if water_station.traditional %}
                        Traditional
                        {% endif %}
                        <!-- Add checkboxes with labels for "Approve" and "Reject" -->
                        <div>
                            <input type="radio" name="radio-group-{{ water_station.id }}" value="approved" id="approve-{{ water_station.id }}">
                            <label for="approve-{{ water_station.id }}">Approve</label>
                            <input type="radio" name="radio-group-{{ water_station.id }}" value="rejected" id="reject-{{ water_station.id }}">
                            <label for="reject-{{ water_station.id }}">Reject</label>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <button type="submit" class="btn btn-primary mb-4">Submit</button>
        </div>
    </form>
{% else %}
    <p class="text-center pt-2">No forms currently need approval review</p>
{% endif %}

<div class="text-center"><a href="{% url 'home' %}" class="btn btn-secondary">Back to Home</a></div>
{% endblock %}

water/templates/base.html
{% load bootstrap5 %}
{% load socialaccount %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        {% if title %}
            <title>{{ title }} | Water App</title>
        {% else %}
            <title>Water App</title>
        {% endif %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
            <div class="container-fluid">
                <a class="navbar-brand text-primary" href="{% url 'home' %}">Water App</a>
                <div class="order-lg-4 order-0" style="margin-left: auto;">
                    {% if user.is_authenticated %}
                    <span style="font-size: 14px;" class="navbar-brand text-secondary">{{ user.first_name }} ({{ user.email }})</span>
                    <span style="font-size: 14px; font-weight: bold;" class="navbar-brand text-secondary">
                        {% if admin %}
                            ADMIN
                        {% endif %}
                    </span>
                {% endif %}
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" id="navitem-home" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="navitem-map" href="{% url 'map' %}">Map</a>
                        </li>
                        {% if user.is_authenticated %} 
                            <li class="nav-item">
                                <a class="nav-link" id="navitem-add" href="{% url 'submit_water_station' %}">
                                    {% if admin %}
                                    Add a New Water Station
                                    {% else %}
                                    Submit a New Water Station
                                    {% endif %}
                                </a>
                            </li>
                            {% if admin %}
                                <li class="nav-item">
                                    <a class="nav-link" id="navitem-approve" href="{% url 'approve_water_station' %}">Approve Water Stations</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" id="navitem-approve" href="{% url 'user_water_stations' %}">View Submitted Stations</a>
                                </li>
                            {% endif %}
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}{% endblock %}
    </body>
</html>

water/templates/error.html
{% extends "base.html" %}
{% load socialaccount %}


{% block content %}
<p class="text-center pt-2"> You don't have access to this page because your account doesn't have permission or you are not logged in. </p>

<form action="{% provider_login_url 'google' %}" method="post">
    {% csrf_token %}
    <div class="text-center my-3">
        <button class="btn btn-primary" type="submit">Login with Google</button>
    </div>
</form>

<div class="text-center"><a href="{% url 'home' %}" class="btn btn-secondary">Go back to home</a></div>
{% endblock %}

water/templates/home.html
{% extends "base.html" %}
{% load socialaccount %}

{% block content %}
<script>
    if ( document.getElementById("navitem-map").classList.contains('active') ) {
        document.getElementById("navitem-map").classList.remove('active');
    }
    if ( ! document.getElementById("navitem-home").classList.contains('active') ) {
        document.getElementById("navitem-home").classList.add('active');
    }
    if ( document.getElementById("navitem-add").classList.contains('active') ) {
        document.getElementById("navitem-add").classList.remove('active');
    }
    if ( document.getElementById("navitem-approve").classList.contains('active') ) {
        document.getElementById("navitem-approve").classList.remove('active');
    }
</script>
<div class="h-75 d-flex align-items-center justify-content-center align-items-center text-center flex-column">     
    <h2 class="p-2">
        Welcome to Water App,<br>an app for finding water stations on grounds.
    </h2>
    {% if user.is_authenticated %}
        {% if admin %}
            <!-- <div class="p-2">Welcome, admin user {{ user.first_name }} ({{ user.email }}).</div> -->
            <div class="p-2"><a href="{% url 'submit_water_station' %}" class="btn btn-primary">Add a New Water Station</a></div> 
            <a href="{% url 'approve_water_station' %}" class="btn btn-primary" >Approve Water Stations</a>
        {% else %}
            <!-- <div class="p-2">Welcome, user {{ user.first_name }} ({{ user.email }}).</div> -->
            <div class="p-2"><a href="{% url 'submit_water_station' %}" class="btn btn-primary">Submit a New Water Station</a></div> 
        {% endif %}
        <div class="p-2"><a class="btn btn-primary" href="{% url 'map' %}"> Go to Map </a></div>
        <div class="p-2"><a class="btn btn-secondary" href="{% url 'logout' %}">Logout</a></div>
    {% else %}
        <div class="p-2"><a class="btn btn-primary" href="{% url 'map' %}"> Go to Map </a></div>
        <form action="{% provider_login_url 'google' %}" method="post">
            {% csrf_token %}
            <div class="text-center">
                <button class="btn btn-primary" type="submit">Login with Google</button>
            </div>
        </form>
        <p class="text-center" style="font-size: 14px;">You are not currently logged in.<br>To submit a new water station, please log in.</p>
    {% endif %}
</div>

{% endblock %}

water/templates/map.html
{% extends "base.html" %}
{% load static %}

<!--REFERENCE: https://developers.google.com/maps/documentation/javascript/advanced-markers/start-->
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'water/map_style.css' %}"/> 
    <div class="flex-container">
        <div id="station-menu">
            {% include "map_stations.html" %}
        </div>
        <div id="map-container">
            <!--map will be rendered here-->
        </div>
    </div>
    <script>
        // REFERENCE: https://developers.google.com/maps/documentation/javascript/controls
        // REFERENCE: https://developers.google.com/maps/documentation/cloud-customization/map-styles
        // REFERENCE: https://developers.google.com/maps/documentation/javascript/examples/place-details
        // REFERENCE: https://developers.google.com/maps/documentation/javascript/examples/event-simple
        window.CSRF_TOKEN = "{{ csrf_token }}";
        function initMap() {
            // render map
            const map = new google.maps.Map(document.getElementById("map-container"), {
                center: {lat:38.0316 , lng: -78.5108},
                zoom: 17.5,
                disableDefaultUI: true,
                mapId: "6db324c6c3e77cd0",
                clickableIcons: false,
            });
            // render markers
            let markers = [];
            let infoWindow = new google.maps.InfoWindow();
            let i = 0;
            // not an error, safe to ignore
            {% for building in buildings %}
                // create marker
                markers[i] = new google.maps.Marker({
                    map: map,
                    position: { lat: {{building.lat}}, lng: {{building.lng}} },
                });
                markers[i].index = i;
                markers[i].addListener("click", () => {
                    $.ajax({
                        type: "GET",
                        url: "{% url 'map_stations' place_id=building.place_id %}",
                        data: {
                            "csrfmiddlewaretoken": "{{csrf_token}}",
                        },
                        success: function(res) {
                            $("#station-menu").html(res);
                        },
                    });
                })
                // add info window
                // REFERENCE: https://stackoverflow.com/questions/8325736/creating-markers-in-loop-infowindow-does-not-open-when-inside-an-click-listene
                google.maps.event.addListener(markers[i], "click", function () {
                    infoWindow.setContent("<p>{{building.name}}</p><a target='_blank' href='https://www.google.com/maps/search/?api=1&query={{building.lat}}%2C{{building.lng}}'>Get directions</a>");
                    infoWindow.open(map, markers[this.index]);
                });
                i++;
            {% endfor %}
            // geolocate user
            const successCallback = (position) => {
                const pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude,
                };
                const userMarker = new google.maps.Marker ({
                    map: map,
                    position: pos,
                    title: "You are here",
                    icon: {
                        path: google.maps.SymbolPath.CIRCLE,
                        scale: 10,
                        fillOpacity: 1,
                        strokeWeight: 2,
                        fillColor: '#5384ED',
                        strokeColor: '#ffffff',
                    },
                });
                const userInfo = new google.maps.InfoWindow({
                    content: "You are here",
                });
                userMarker.addListener("click", () => {
                    userInfo.open({
                        anchor: userMarker,
                        map,
                    });
                });
            };

            const errorCallback = (error) => {
                console.log(error);
            };

            navigator.geolocation.getCurrentPosition(successCallback, errorCallback);
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key={{key}}&callback=initMap" async defer></script>
    <script>
        if ( document.getElementById("navitem-home").classList.contains('active') ) {
            document.getElementById("navitem-home").classList.remove('active');
        }
        if ( ! document.getElementById("navitem-map").classList.contains('active') ) {
            document.getElementById("navitem-map").classList.add('active');
        }
        if ( document.getElementById("navitem-add").classList.contains('active') ) {
            document.getElementById("navitem-add").classList.remove('active');
        }
        if ( document.getElementById("navitem-approve").classList.contains('active') ) {
            document.getElementById("navitem-approve").classList.remove('active');
        }
    </script>
{% endblock %}

water/templates/map_stations.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

<p class="mt-md text-center" style="padding: 18px 18px 0px 18px; font-size:0.8rem">To see your location on the map, allow location permissions when prompted by your browser.</p>
<hr>

{% if stations %}
    <h3 style="margin-bottom: 12px; padding: 18px;">{{ stations.0.building.name }}</h3>
    <div class="accordion" id="accordionExample">
    {% for floor in floors %}
        <div class="accordion-item">
            <h4 class="accordion-header" id="heading{{forloop.counter}}">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{forloop.counter}}" aria-expanded="false" aria-controls="collapse{{forloop.counter}}">
                    {% if floor.floor == 0 %}
                        Basement
                    {% else %}
                        Floor {{ floor.floor }}
                    {% endif %}
                </button>
            </h4>
            <div id="collapse{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="heading{{forloop.counter}}" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                {% for station in stations %}
                    {% if station.floor == floor.floor %}
                        <div style="max-width: 45%; min-width: 35%;">
                            <b>Station {{ station.id }}</b>
                        </div>
                                <ul class="station-info-list">
                                    <li>
                                        <b>Area: </b>
                                        {% if station.cardinal == "c" %}
                                            Central area of the building
                                        {% elif station.cardinal == "n" %}
                                            North side of the building
                                        {% elif station.cardinal == "s" %}
                                            South side of the building
                                        {% elif station.cardinal == "e" %}
                                            East side of the building
                                        {% elif station.cardinal == "w" %}
                                            West side of the building
                                        {% endif %}
                                    </li>
                                    <li>
                                        <b>Dispenser: </b>
                                        {% if station.traditional and station.bottle %}
                                            Drinking and bottle refill
                                        {% elif station.traditional %}
                                            Drinking
                                        {% else %}
                                            Bottle refill
                                        {% endif %}
                                        <br/><br/>
                                    </li>
                                </ul>
                    {% endif %}
                {% endfor %}
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% else %}
    <p style="padding: 18px; text-align: center;">Select a pin to see water stations in the building</p>
    <p class="mt-md text-center" style="padding: 0px 18px 18px 18px;">
        This app currently covers all water stations on Engineering Way (from Rice through Thornton Hall).
        <br>The scope may expand in the future to cover further ground.
    </p>
{% endif %}

water/templates/user_water_stations.html
{% extends "base.html" %}
{% block content %}
    <h2 class="text-center pt-2">Your Submitted Water Stations</h2>
    {% if user_water_stations %}
        <div class="container">
            <div class="row">

                <div class="col-md-6">
                    <h4 class="text-center">Approved Stations</h4>
                    <div class="bg-light text-black text-center mx-auto w-100 border border-2 mt-4">
                        <ul class="list-unstyled">
                            {% for station in user_water_stations %}
                                {% if station.approved %}
                                    <li class="mb-4 mt-2">
                                        Building: {{ station.building.name }}
                                        <br>
                                        Floor: {{ station.floor }}
                                        <br>
                                        Area: {{ station.get_cardinal_display }}
                                        <br>
                                        Dispenser:
                                        {% if station.traditional and station.bottle %}
                                            Drinking and bottle refill
                                        {% elif station.traditional %}
                                            Drinking
                                        {% else %}
                                            Bottle refill
                                        {% endif %}
                                        <br>
                                        <span style="color: green; font-weight: bold;">(Approved)</span>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                
                <div class="col-md-6">
                    <h4 class="text-center">Pending Approval</h4>
                    <div class="bg-light text-black text-center mx-auto w-100 border border-2 mt-4">
                        <ul class="list-unstyled">
                            {% for station in user_water_stations %}
                                {% if not station.approved %}
                                    <li class="mb-4 mt-2">
                                        Building: {{ station.building.name }}
                                        <br>
                                        Floor: {{ station.floor }}
                                        <br>
                                        Area: {{ station.get_cardinal_display }}
                                        <br>
                                        Dispenser: {{ station.get_dispenser_display }}
                                        <br>
                                        <span style="color: red; font-weight: bold;">(Pending Approval)</span>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <p class="text-center pt-2">You haven't submitted any water stations yet.</p>
    {% endif %}
    <br>
    <div class="text-center"><a href="{% url 'submit_water_station' %}" class="btn btn-primary">Back to Submit a Station</a></div>
    <br>
    <div class="text-center"><a href="{% url 'home' %}" class="btn btn-secondary">Back to Home</a></div>
    <br>
{% endblock %}